// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNqrph-xCk2PB3uylFmxjNuPzqcPsWLok',
    appId: '1:588414711624:web:db7209eb55f6886b92657d',
    messagingSenderId: '588414711624',
    projectId: 'wildguardsentinel-b3c9c',
    authDomain: 'wildguardsentinel-b3c9c.firebaseapp.com',
    storageBucket: 'wildguardsentinel-b3c9c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCa3YHKn6z5WxPL0aJV5GAxy_Jn57mAWy8',
    appId: '1:588414711624:android:457223444398c03d92657d',
    messagingSenderId: '588414711624',
    projectId: 'wildguardsentinel-b3c9c',
    storageBucket: 'wildguardsentinel-b3c9c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBMnye5HcJyQrOth8TyyoaBLnFgCaIxOc',
    appId: '1:588414711624:ios:9abc186a4c4e90a792657d',
    messagingSenderId: '588414711624',
    projectId: 'wildguardsentinel-b3c9c',
    storageBucket: 'wildguardsentinel-b3c9c.firebasestorage.app',
    iosBundleId: 'com.example.wildguard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBMnye5HcJyQrOth8TyyoaBLnFgCaIxOc',
    appId: '1:588414711624:ios:9abc186a4c4e90a792657d',
    messagingSenderId: '588414711624',
    projectId: 'wildguardsentinel-b3c9c',
    storageBucket: 'wildguardsentinel-b3c9c.firebasestorage.app',
    iosBundleId: 'com.example.wildguard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNqrph-xCk2PB3uylFmxjNuPzqcPsWLok',
    appId: '1:588414711624:web:4a9baef1375948c192657d',
    messagingSenderId: '588414711624',
    projectId: 'wildguardsentinel-b3c9c',
    authDomain: 'wildguardsentinel-b3c9c.firebaseapp.com',
    storageBucket: 'wildguardsentinel-b3c9c.firebasestorage.app',
  );
}
